<?php $faqs = $block->getFaqs(); ?>

<section class="question-wrapper type-product <?= $block->getStyle()?>" itemscope itemtype="https://schema.org/FAQPage">
    <?php foreach($faqs as $faq): ?>
        <div class="question-body" data-ident="<?= $faq->getIdent() ?? 'ask-'.$faq->getId(); ?>" data-faqorder="<?= $faq->getOrder() ?? 0;?>" itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
            <div class="question-title" itemprop="name"><?= $faq->getFaq();?></div>
            <div class="question-answer" itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">
                <div itemprop="text"><?= $block->getHtmlVal($faq->getAnswer());?></div>
            </div>
        </div>
    <?php endforeach; ?>
</section>
